n = input('Digite qualquer coisa: ')
print('Qual o tipo primitivo do que foi digitado?', (type(n)))
print('Somente tem espaços?', n.isspace())
print('O que foi digitado só contém iten(s) numéricos? ')
print(n.isnumeric())
print('O que foi digitado só contém iten(s) do alfabeto? ')
print(n.isalpha())
print('O que foi digitado é do alfabeto e/ou numérico? ')
print(n.isalnum())
print('O que foi digitado está totalmente com letras maiúsculas? ')
print(n.isupper())
print('O que foi digitado está totalmente com letras minúsculas? ')
print(n.islower())
print('O que foi digitado é decimal? ')
print(n.isdecimal())
print('Está capitalizado?', n.istitle())
# Teste com o valor booleano!
n1 = bool(input('Digite qualquer outra coisa: '))
print('O que foi digitado é um valor booleano? ')
print(n1)
